# Generated by Django 4.0.1 on 2023-03-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ucontact',
            new_name='upass',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
