# Generated by Django 4.0.1 on 2023-03-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_ucontact_user_upass_remove_user_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='uname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='upass',
            new_name='password',
        ),
    ]
