# Generated by Django 4.0.1 on 2023-04-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_rename_uemail_user_email_rename_uname_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=100)),
                ('workexp', models.CharField(max_length=100)),
                ('bins', models.CharField(max_length=50)),
                ('by', models.IntegerField()),
                ('iins', models.CharField(max_length=50)),
                ('iy', models.IntegerField()),
                ('sins', models.CharField(max_length=50)),
                ('sy', models.IntegerField()),
                ('skills', models.CharField(max_length=100)),
                ('certifications', models.CharField(max_length=100)),
                ('achievements', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'resume',
            },
        ),
    ]
